#!/bin/bash

## #ddev-generated
## Description: Run ESLint
## Usage: eslint
## Example: ddev eslint

cd /var/www/html/web/core;
yarn eslint --no-error-on-unmatched-pattern --resolve-plugins-relative-to=web/core ../../$@
