#!/bin/bash

## #ddev-generated
## Description: Run PHPCBF
## Usage: phpcbf
## Example: ddev phpcbf

/var/www/html/vendor/bin/phpcbf --standard="Drupal,DrupalPractice" --extensions="php,module,inc,install,test,profile,theme" $@

