#!/bin/bash

## Description: Runs phpunit tests
## Usage: phpunit
## Example: "ddev phpunit path/to/tests"
## Example: "ddev phpunit --testsuite=unit"

# Disable Xdebug to speed up test executions and to avoid debugger connection
# problems.
#disable_xdebug

if ! command -v phpunit >/dev/null; then
  echo "phpunit is not in PATH in the web container. You probably forgot to 'ddev composer install'"
  exit 2
fi
echo "Clearing old webdriver sessions"
curl -f -s http://selenium-chrome:4444/status | jq -r '.value.nodes[].slots[].session.sessionId' | while read -r session; do if [ "$session" != "null" ]; then curl -X DELETE "http://selenium-chrome:4444/session/$session"; fi; done

# Run tests.
cd /var/www/html
phpunit --process-isolation $@
